name: Create Joomla installation package

on:
  release:
    types: [ published ]

jobs:

  createReleasePackage:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compare release and manifest versions
        id: check-versions
        run: |
          MANIFEST_VERSION=$(awk -F'[<>]' '/<version>/ {print $3}' ./jinterventionimage.xml)
          RELEASE_VERSION=${{ github.ref_name }}
          if [ "$MANIFEST_VERSION" != "$RELEASE_VERSION" ]; then
            echo "Error: The release version must match the version specified in the manifest."
            exit 1
          fi

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install git zip unzip curl jq -y

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          tools: composer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install composer dependencies from source
        run: composer install --prefer-dist --no-dev --no-progress --optimize-autoloader

      - name: Run build script
        run: |
          export TERM=xterm
          zip -r lib_jinterventionimage.zip src vendor jinterventionimage.xml

      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: lib_jinterventionimage.zip
